spring:
  datasource:
    url: jdbc:mysql://localhost/ecommerce
    username: root
    password: q9s5c1@q9w8e7
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
